"""Translation cache — stores AI-generated translations for keyword expansion.

Each row maps a normalised keyword to its FR/NL/EN translations,
generated by Claude Haiku and cached permanently.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Index, String, Text
from app.models.base import Base


class TranslationCache(Base):
    __tablename__ = "translation_cache"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    keyword_normalised = Column(String(200), nullable=False, unique=True, index=True)
    keyword_original = Column(String(200), nullable=False)
    fr = Column(Text, nullable=True)   # JSON array: ["nettoyage", "nettoyage industriel"]
    nl = Column(Text, nullable=True)   # JSON array: ["schoonmaak", "industriële reiniging"]
    en = Column(Text, nullable=True)   # JSON array: ["cleaning", "industrial cleaning"]
    source = Column(String(20), nullable=False, default="ai")  # "static" or "ai"
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index("ix_translation_cache_keyword", "keyword_normalised"),
    )

    def __repr__(self) -> str:
        return f"<TranslationCache '{self.keyword_original}' ({self.source})>"
